Add index.html
ok-technopolis-autumn-2022/Alexander_Peskov pull request #1
Opened 2022-10-02 22:31 UTC by aosandy

2022-10-03 08:08 UTC, fromanywhere requested changes
Неплохо. После сегодняшней лекции дорабатываем в этом же PR

2022-10-03 08:08 UTC, fromanywhere commented on index.html
> +        <input type="text" placeholder="What needs to be done?">
Кнопка потеряна

2022-10-03 08:08 UTC, fromanywhere commented on index.html
> +                <input type="checkbox" id="task1" name="task1">
Есть ли смысл в name?

2022-10-10 11:13 UTC, aosandy commented on index.html
> +        <input type="text" placeholder="What needs to be done?">
Добавил 4dd95b66f856b331333a5b64b39f5b9b30ac39fd

2022-10-10 11:13 UTC, aosandy commented on index.html
> +                <input type="checkbox" id="task1" name="task1">
Исправил 4dd95b66f856b331333a5b64b39f5b9b30ac39fd

2022-10-10 11:16 UTC, fromanywhere requested changes

2022-10-10 11:16 UTC, fromanywhere commented on index.html
> +                <button class="select-all" aria-label="Select all tasks"></button>
лучше title, чтобы обычные люди тоже могли понять, что означает иконка

2022-10-10 11:16 UTC, fromanywhere commented on index.html
> +                            <button class="delete-task"></button>
тут тоже title

2022-10-10 11:16 UTC, fromanywhere commented on index.html
> +                <section class="switches" aria-label="Filter tasks">
role="radiogroup"

2022-10-16 18:52 UTC, aosandy commented on index.html
> +                <section class="switches" aria-label="Filter tasks">
Исправил 8c3af4eb9fa5ad4daa196cfecbc3fbe56a631fe3

2022-10-16 18:52 UTC, aosandy commented on index.html
> +                            <button class="delete-task"></button>
Исправил 8c3af4eb9fa5ad4daa196cfecbc3fbe56a631fe3

2022-10-16 18:52 UTC, aosandy commented on index.html
> +                <button class="select-all" aria-label="Select all tasks"></button>
Исправил 8c3af4eb9fa5ad4daa196cfecbc3fbe56a631fe3

2022-10-17 07:55 UTC, fromanywhere approved these changes

2022-10-17 08:05 UTC, merged