Homework 2: Add style
ok-technopolis-autumn-2022/Alexander_Peskov pull request #2
Opened 2022-10-31 13:43 UTC by aosandy

## Приложение с CSS: ##
![image](https://user-images.githubusercontent.com/73636600/199021643-3b95d536-1d04-48fc-8def-109b3f9b3ca6.png)
Прошу прощения за задержку в сдаче задания

2022-10-31 15:15 UTC, fromanywhere requested changes

2022-10-31 15:15 UTC, fromanywhere commented on style/style.css
> +    color: #666666;
flex-grow не хватает 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/1042969/199041905-efea40bf-adb8-40bb-9f35-07466c57f340.png">

2022-10-31 15:15 UTC, fromanywhere commented on style/style.css
> +    vertical-align: 50%;
может быть вот так 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/1042969/199042237-e4466223-b379-4654-a24a-d46c00337904.png">

2022-10-31 15:15 UTC, fromanywhere commented on style/style.css
> +    font-family: 'Roboto', serif;
почему-то поле ввода не на всю ширину 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/1042969/199042435-19ae912a-4a31-462f-91e5-991b92062493.png">

2022-10-31 15:15 UTC, fromanywhere commented on style/style.css
> +    border: 1px solid #EBDFDF;
фильтры прыгают по горизонтали при переключении

2022-10-31 15:15 UTC, fromanywhere commented on style/style.css
> +    color: #888888;;
;

2022-10-31 15:15 UTC, fromanywhere commented on style/style.css
> +    border: 0px #000 solid;
делаем кнопку больше за счет высоты 
<img width="191" alt="image" src="https://user-images.githubusercontent.com/1042969/199042691-7a2fae12-1982-4f6c-9c1c-feb87878f3b9.png">

2022-10-31 15:15 UTC, fromanywhere commented on index.html
>                          <input type="radio" name="switch" aria-label="Select all tasks">
checked

2022-11-05 08:29 UTC, aosandy commented on index.html
>                          <input type="radio" name="switch" aria-label="Select all tasks">
Исправил все ошибки в d640edc2f7df722a3be45a140cf1d3763dd89a75

2022-11-05 21:01 UTC, fromanywhere commented
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1042969/200141006-8d5aab7b-4190-47b2-a28e-60148cc6c15b.png">

Если текста много, то будет как снизу, а хочется, чтобы как сверху.
Можно было бы оставить Вам это на самостоятельное изучение, но тут на Вашей вёрстке есть нюанс, об который Вы закопаете много времени, поэтому я подскажу

На флексовых контейнерах бывают сложности с переполненнием контейнера — они могут плохо понимать свою максимальную ширину. Парадоксально, но для решения это проблемы следует писать конструкцию с min-width.

Вешаем на label примерно такое { min-width: 0;display: flex;align-items: center; } (флекс с центровкой тут — исключительно в косметических целях). 

Чекбокс теперь начнет страдать от нехватки места, поможем ему { flex-shrink: 0; }

task-item__text будет всё еще вести себя нескромно — поставим его на место { overflow: hidden; text-overflow: ellipsis; }

Кстати, я не буду цепляться к Вашему решению стилизации чекбокса через { appearance: none; }, но учтите, что в Safari это не заработает (а как заработает, показывали на лекции)

2022-11-06 17:46 UTC, aosandy commented
> <img alt="image" width="633" src="https://user-images.githubusercontent.com/1042969/200141006-8d5aab7b-4190-47b2-a28e-60148cc6c15b.png">
> 
> Если текста много, то будет как снизу, а хочется, чтобы как сверху. Можно было бы оставить Вам это на самостоятельное изучение, но тут на Вашей вёрстке есть нюанс, об который Вы закопаете много времени, поэтому я подскажу
> 
> На флексовых контейнерах бывают сложности с переполненнием контейнера — они могут плохо понимать свою максимальную ширину. Парадоксально, но для решения это проблемы следует писать конструкцию с min-width.
> 
> Вешаем на label примерно такое { min-width: 0;display: flex;align-items: center; } (флекс с центровкой тут — исключительно в косметических целях).
> 
> Чекбокс теперь начнет страдать от нехватки места, поможем ему { flex-shrink: 0; }
> 
> task-item__text будет всё еще вести себя нескромно — поставим его на место { overflow: hidden; text-overflow: ellipsis; }
> 
> Кстати, я не буду цепляться к Вашему решению стилизации чекбокса через { appearance: none; }, но учтите, что в Safari это не заработает (а как заработает, показывали на лекции)

Исправил в 68b45be8d77878521d2a9ea50055344dfdee058c, спасибо за объяснение!

2022-11-06 21:23 UTC, fromanywhere approved these changes

2022-11-07 10:14 UTC, merged