Part 4: Add JS
ok-technopolis-autumn-2022/Alexander_Peskov pull request #4
Opened 2022-11-26 16:25 UTC by aosandy

2022-11-28 08:49 UTC, fromanywhere requested changes
Сравните, пожалуйста, логику работы Вашего счетчика с любой реализацией отсюда https://todomvc.com/

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +var itemsCounter;
Стараемся не использовать var. Как по мне, в этом нет ничего страшного, но в «модных» компаниях на Вас будут косо смотреть

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +window.onload = function() {
лучше на DOMContentLoaded, а еще лучше просто подключить js как defer

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +        var itemsCount = 0;
С архитектурной точки зрения я бы не рекомендовал отдельно хранить количество элементов, а делать это значение вычисляемым относительно существующей модели. Иначе это всё нужно синхронизировать, рано или поздно это обязательно разойдется и будет долго и увлекательно искать ошибку

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +    for (var i = 0; i < todolist.length; i++) {
Тут строится рендер на основе модели (данных). Давайте это вынесем в отдельную функцию (стараемся сразу по возможности разделять работу с данными и отображение)

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +    if (e.target.todoText.value == '') {
давайте тогда уже сразу e.target.todoText.value.trim()

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +    if (e.target.todoText.value == '') {
а вообще const text = e.target.todoText.value.trim(), и дальше с ним работать (чтобы не ходить внутри рантайма по цепочке полей каждый раз)

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +    button.addEventListener('click', deleteTask);
Давайте уберем за делегиирование, чтобы обработчик был один на весь список, а не на каждый элемент

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +    for (var i = 0; i < children.length; i++) {
const allChecked = ![...children].some(child => isActive(child))

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +    changeItemsCount(-deletedCounter);
Как было бы проще, если бы changeItemsCount был без аргумента, ну или уже тогда зависел только от todolist и filterMode. Тогда не нужно считать, на сколько единиц произошло изменение, модифицировать только todolist и затем его перерисовывать

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +function updateTaskStatusInLocalStorage(id, checked) {
Ну вот сложно же так работать с хранилищем — отдельно в нем удалять, отдельно обновлять. Может, проще просто перезаписывать его целиком каждый раз? (это не особо дорого)

2022-11-28 08:49 UTC, fromanywhere commented on src/index.js
> +            child.style.display = "block";
для этого придумали css и classList

2022-12-04 12:05 UTC, aosandy commented
Исправил ошибки в 10ad396dee22f30946f512fb25373abc6cc96165

2022-12-04 12:20 UTC, aosandy commented
> Сравните, пожалуйста, логику работы Вашего счетчика с любой реализацией отсюда https://todomvc.com/

Изменил логику работы счетчика - теперь он уменьшается при выполнении задачи, а не только при ее удалении

2022-12-05 09:34 UTC, fromanywhere approved these changes

2022-12-05 09:34 UTC, fromanywhere commented on src/index.js
> +    if (text == '') {
всегда только строгое ===

2022-12-05 09:34 UTC, fromanywhere commented on src/index.js
> +            i--;
тут слишком сложно с двойным декрементом. Возьмите while(length--)

2022-12-05 09:34 UTC, fromanywhere commented on src/index.js
> +    const hidden = "hidden";
я бы вынес декларацию за тело функции

2022-12-05 13:04 UTC, merged